### PR TITLE
Challenge One

### PR DESCRIPTION
**Pull request by machariamarigi**
**What does this pull request do**
This pull request is to show my completion of the Andela 21 Bootcamp challenge one where I was supposed to come up with a UI design for a shopping list app.

**Where the reviewer should start**
The HTML templates may be found at ```*/designs/templates/**```
The CSS file may be found at ```*/designs/static/css/style.css```

**Extra Info**
The folder structure has been designed to mimic common flask HTML/CSS folder structure.

**Screenshots**
landing_page

register_page

login_page

dashboard

single_shoppinglist

### CODE REVIEW

**Comment by Chris-Maina** [comment]
Great git flow, check out the PR guidelines below
https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices

**Comment by machariamarigi** [comment]
Thanks @Chris-Maina for the link

**Comment by parseen254** [comment]
Nice Macharia Good work

**Comment by JayKay24** [comment]
Great overall design. You could try aligning your input elements and labels for greater visual appeal. You could also try prefixing your commit messages with the nature of the actual task done. e.g '[CHORE] Add Travis CI badge to README.md file'. We have chore, fix, feature etc

**Pull request merged**
